apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default (include "my-app.fullname" .) .Values.deploymentName }}
  labels:
    helm.sh/chart: {{ include "my-app.chart" . }}
    app.kubernetes.io/name: {{ include "my-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "my-app.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "my-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DB_HOST
              value: {{ .Values.env.dbHost }}
            - name: DB_USER
              value: {{ .Values.env.dbUser }}
            - name: DB_PASSWORD
              value: {{ .Values.env.dbPassword }}
            - name: DB_DATABASE
              value: {{ .Values.env.dbDatabase }}
      restartPolicy: Always
